spring:
  application:
    name: patient-service

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: ${CONFIG_SERVER_URIS}

server:
  port: 8082   # <-- මෙතන port එක assign කරලා තියෙන්න

eureka:
  instance:
    hostname: ${HOSTNAME}
    instance-id: ${spring.application.name}:${HOSTNAME}:${server.port}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URLS}